### ISSUE TITLE
Add neptune.ai

### ISSUE THREAD

**Issue by InCogNiTo124** [zszazi/Deep-learning-in-cloud#19]
\*title*

**Comment by InCogNiTo124** [comment]
I'll do it in the next week

**Comment by zszazi** [comment]
> I'll do it in the next week

[Done and merged to master ](
https://github.com/zszazi/Deep-learning-in-cloud/commit/054703b9a9b311625c0eaf0011b7aaa9c1002b79#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
