### ISSUE TITLE
Suggestion: getting rid of the row number column

### ISSUE THREAD

**Issue by InCogNiTo124** [zszazi/Deep-learning-in-cloud#36]
How about we get rid of the `#` column? I don't see it really useful, and if we get rid of it our commits and changes will be smaller since it is trivial to just insert into a sorted list without changing every index below

**Comment by zszazi** [comment]
Sure I too think it's better to get rid of it
Let me do changes for it, or if you have already done with it, do push it .

Meanwhile I am thinking to add number of entries in both cloud and mlops right below the last updated line? Your thoughts?

**Comment by InCogNiTo124** [comment]
> Sure I too think it's better to get rid of it Let me do changes for it, or if you have already done with it, do push it .
> 
> Meanwhile I am thinking to add number of entries in both cloud and mlops right below the last updated line? Your thoughts @InCogNiTo124 ?

you do changes, I haven't come around for that yet

I would only suggest adding the entry count _ABOVE_ the section, it seems better to me to know how many entries there is immediately, and not at the end :sweat_smile:
