### ISSUE TITLE
Add TensorDock

### ISSUE THREAD

**Issue by jonathan-lei** [zszazi/Deep-learning-in-cloud#39]
Hey! Jonathan from TensorDock here.

Can you add us to the "Deep-learning-in-cloud" section?
Cloud Vendor: TensorDock
Website: https://tensordock.com/
Pricing: https://tensordock.com/pricing and https://console.tensordock.com/deploy (pay-per-resource, starting at $0.32/hour for an RTX 4000 or $0.57/hour for a V100)

We also sometimes provide discounted pricing and free credits to open source projects, students, and researchers on request, if you want to add this to the "Perks and offers" section. 

Side note: VectorDash is out of operation now. I don't know about Onepanel, Omnisci, and Neuro Ai, but their websites don't work for me, so you might want to take a look, if you want to remove them. 

Thanks!

**Comment by InCogNiTo124** [comment]
Hello, thanks for letting us know about your company :smile: we'll add it as soon as we're able to

> Side note: VectorDash is out of operation now. I don't know about Onepanel, Omnisci, and Neuro Ai, but their websites don't work for me, so you might want to take a look, if you want to remove them.

That is valuable info, we'll clean it up, thanks ^^

**Comment by zszazi** [comment]
Thanks @InCogNiTo124 for actively maintaining this repo, you are doing great work
